[build]
    publish = "public"
    command = "hugo --gc --minify"

[build.environment]
    HUGO_VERSION = "0.134.2"

[context.production.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
    command = "hugo -D -F -b $DEPLOY_PRIME_URL/"

[context.branch-deploy]
    command = "hugo -D -F -b $DEPLOY_PRIME_URL/"